config/routes.rb
Nooch::Application.routes.draw do
  resources :jobs

  get "pages/home"

  resources :applicants

  get "pages/home"

  get "pages/contact"

  get "pages/products"

  root :to => 'pages#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :email, :linkedin, :name, :why

  validates :email, presence: true
  validates :linkedin, presence: true
  validates :name, presence: true
  validates :why, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to root_path, notice: 'Your application was successfully submitted.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def products
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "LinkedIn" %><br />
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label "Why do you want to join Nooch Labs?" %><br />
    <%= f.text_area :why %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <%= submit_tag 'Apply to Nooch', :class => 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Linkedin</th>
    <th>Why</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.name %></td>
    <td><%= job.linkedin %></td>
    <td><%= job.why %></td>
    <td><%= job.email %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<div class="container">
<div class="row">
	  <div class="span8">
		<h2>Join the Nooch Team</h2>

			<%= render 'form' %>

	</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @job.name %>
</p>

<p>
  <b>Linkedin:</b>
  <%= @job.linkedin %>
</p>

<p>
  <b>Why:</b>
  <%= @job.why %>
</p>

<p>
  <b>Email:</b>
  <%= @job.email %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nooch Labs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--for responsive bootstrap -->
</head>
<body>
</div>
<div class="container">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="<%=root_path%>">nooch labs</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        
      		</ul>
      		<ul class="nav pull-right">
      		<li class="divider-vertical"></li>
      		<li><%= link_to "Join Nooch", new_job_path %></li>
      		<li><%= link_to "Products", pages_products_path %></li>
      		<li><%= link_to "Contact", pages_contact_path %></li>
    		</ul>      
      </div>
 
    </div>
  </div>
</div>
</div>

<%= yield %>

</body>
</html>

app/views/pages/contact.html.erb
<div class="container">
	<div class="row">
	  <div class="span8">
<h2>Contact nooch labs</h2>
<p>You can contact us at info@noochlabs.com.</p>
</center>
</div>

app/views/pages/home.html.erb
<div class="container">
<div class="row">
	  <div class="span6">
<center><h1 style="color:#F2F2F2">nooch labs</h1></center>
</br></br>
  <div class="span6">
<p>We're a team of smart and passionate entrepreneurs in Silicon Valley who 
love experimenting with building cool products that solve real problems.
Our methodology for creating new products involves ensuring that the product has
potential virality or revenue from day 1, and a metric to benchmark the minimal viable product's success prior to building the full feature.</p>
  <center><%= link_to 'Apply to Nooch', new_job_path, :class => 'btn btn-large btn-primary' %></center>
</div>

app/views/pages/products.html.erb
<div class="container">
	<div class="row">
	  <div class="span8">
		<h4>Products nooch team members have been previously involved with.</h4>
		<center><p>Coming soon.</p></center>


	</div>